name: CI - Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
      # Nettoyer les caches Python pour éviter les problèmes de permission
      - name: Clean repo
        run: sudo find $GITHUB_WORKSPACE -type d -name "__pycache__" -exec rm -rf {} +
      # Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Installer Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Créer le fichier .env
      - name: Create .env file
        run: |
          echo "MYSQL_HOST=mysql" > .env
          echo "MYSQL_DB_NAME=mydb" >> .env
          echo "DB_USERNAME=user" >> .env
          echo "DB_PASSWORD=pass" >> .env
          echo "MONGODB_HOST=mongo" >> .env

      # Installer les dépendances Python
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest mysql-connector-python pymongo python-dotenv

      # Reset complet de l'environnement Docker et lancement des services
      - name: Start services with Docker Compose
        run: |
          docker-compose down -v
          docker-compose up -d
          echo "Waiting for MySQL to be ready..."
          for i in {1..30}; do
            if docker exec $(docker ps -qf "name=mysql") mysql -uuser -ppass -e "USE mydb;" &> /dev/null; then
              echo "MySQL ready!"
              break
            fi
            echo "MySQL not ready yet, waiting..."
            sleep 2
          done

      # Initialiser la base MySQL
      - name: Initialize MySQL database
        run: |
          docker exec $(docker ps -qf "name=mysql") sh -c "mysql -uuser -ppass mydb < /docker-entrypoint-initdb.d/init.sql"

      # Lancer les tests Python
      - name: Run tests
        run: pytest src/tests
