name: LAB01 CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and start Docker containers
        run: docker-compose up -d --build

      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to start..."
          sleep 20  # donne le temps à MySQL de démarrer

      - name: Initialize MySQL database
        run: docker exec -i log430-a25-labo1-store_manager_app-1 python src/init_db.py

      - name: Run tests
        run: docker exec -i log430-a25-labo1-store_manager_app-1 pytest src/tests

      - name: Shutdown Docker containers
        run: docker-compose down
